using ProyectoFinal.BDA.Equipo10.DataModel;
using System.Collections.ObjectModel;
using Xamarin.Forms;
using Xamarin.Forms.Xaml;

namespace ProyectoFinal.BDA.Equipo10.Pages
{
    [XamlCompilation(XamlCompilationOptions.Compile)]
    public partial class Actrices : ContentPage
    {
        ObservableCollection<Actriz> grupo2;
        public Actrices()
        {
            InitializeComponent();
            
            //A continuacion se crea una nueva ObservableCollection, esto para poner a las actrices, usaremos el Binding para mostrar los datos


 grupo2 = new ObservableCollection<Actriz>
            {
                new Actriz{ Nombre = "Scarlett Johansson", Foto = "actriz1.jpg", Desc = "Scarlett Ingrid Johansson es una actriz, cantante, directora, productora y empresaria estadounidense. Comenzó a mostrar intereses en la actuación desde temprana edad, y a lo largo de su infancia y adolescencia se formó en distintos institutos como actriz.", LargeDesc = "Scarlett Ingrid Johansson (Nueva York; 22 de noviembre de 1984) es una actriz, cantante, directora, productora y empresaria estadounidense. Comenzó a mostrar intereses en la actuación desde temprana edad, y a lo largo de su infancia y adolescencia se formó en distintos institutos como actriz. Tras tener varios papeles secundarios en distintas producciones, obtuvo su primer protagónico a los once años con la película Manny & Lo (1996), a la que luego le siguieron The Horse Whisperer (1998) y Ghost World (2001), actuaciones que le valieron elogios de la crítica. Al cumplir los dieciocho, Johansson comenzó a enfocarse en papeles más maduros y protagonizó las cintas Lost in Translation (2003) y Girl with a Pearl Earring (2003), con las cuales ganó un premio BAFTA y fue nominada a dos Globos de Oro. Poco después, obtuvo dos nominaciones más al Globo de Oro por A Love Song for Bobby Long (2004) y Match Point(2005).Posteriormente, inició una carrera como cantante con la publicación de sus álbumes Anywhere I Lay My Head(2008) y Break Up(2009), que ingresaron al Billboard 200 de los Estados Unidos.En 2010, actuó en una obra de A View from the Bridge y ganó un premio Tony.Además de ello, protagonizó la cinta Marriage Story(2020) y coprotagonizó Jojo Rabbit(2020), actuaciones con las que recibió sus dos primeras nominaciones a los premios Óscar.Como actriz de voz, Johansson participó en películas como The SpongeBob SquarePants Movie(2004), Her(2013), Sing(2016), The Jungle Book(2016), Isle of Dogs(2018), entre otras. "},
                new Actriz{ Nombre = "Natalie Portman", Foto = "actriz2.jpg", Desc = "Natalie Portman Millepied es una actriz, directora, productora y psicóloga israelí nacionalizada estadounidense. Es una de las pocas actrices que ha ganado los cuatro premios más importantes del cine por una misma película", LargeDesc = "Natalie Portman Millepied (nacida Neta-Lee Hershlag; en hebreo, נטע-לי הרשלג‎; Jerusalén, 9 de junio de 1981) es una actriz, directora, productora y psicóloga israelí nacionalizada estadounidense. Es una de las pocas actrices que ha ganado los cuatro premios más importantes del cine por una misma película: el Óscar (Mejor Actriz), el BAFTA (a la mejor actriz), el Globo de oro (a la mejor actriz en un drama) y el Premio del Sindicato de Actores (a la mejor actriz protagonista) por su trabajo en Black Swan (2010) del director Darren Aronofsky. Debutó en el cine en la película francesa Léon (1994), donde encarnó el papel de una huérfana que es salvada por un asesino a sueldo. En la década de 1990, interpretó varios papeles protagonistas en filmes como Beautiful Girls y Anywhere But Here. En 1999, mientras trabajaba en la filmación de Star Wars, ingresó en la Universidad de Harvard en la carrera de psicología, especialidad psicología educativa y obtuvo su licenciatura en 2003. Prosiguió sus estudios en el Yale, donde amplió su estudios de doctorado en psicología educativa."},
                new Actriz{ Nombre = "Emma Watson", Foto = "actriz3.jpg", Desc = "Emma Charlotte Duerre Watson es una actriz, modelo y activista británica nacida en Francia, conocida principalmente por haber interpretado el personaje de Hermione Granger en la saga de películas de Harry Potter.", LargeDesc = "Emma Charlotte Duerre Watson (París, 15 de abril de 1990) es una actriz, modelo y activista británica nacida en Francia, conocida principalmente por haber interpretado el personaje de Hermione Granger en la saga de películas de Harry Potter. Watson fue elegida para interpretar a Hermione a la edad de nueve años, después de haber participado anteriormente solo en obras de teatro escolares. Protagonizó, junto con Daniel Radcliffe y Rupert Grint, las ocho películas de la serie cinematográfica. Debido a su trabajo en Harry Potter, ha sido galardonada con varios premios y se estima que ha ganado 26 millones de libras esterlinas. Watson hizo su primera aparición fuera de Harry Potter en el telefilme Ballet Shoes transmitido por la BBC One el 26 de diciembre de 2007 y obtuvo una audiencia de 5,2 millones. En 2008, prestó su voz para la Princesa Pea en la película animada The Tale of Despereaux, basada en el libro homónimo de Kate DiCamillo. En 2011 participó en My Week with Marilyn, su primer trabajo después de finalizar la saga de Harry Potter. En 2012 protagonizó junto a Logan Lerman, la película The Perks of Being a Wallflower, basada en la novela homónima de Stephen Chbosky, en 2013 actuó en The Bling Ring, película de Sofia Coppola basada en hechos reales, y en 2014 apareció en Noé, la epopeya bíblica de Darren Aronofsky."},
                new Actriz{ Nombre = "Angelina Jolie", Foto = "actriz4.jpg", Desc = "Angelina Jolie Voight es una actriz, cineasta y embajadora de buena voluntad estadounidense. A lo largo de su carrera, Jolie ha recibido varios reconocimientos por sus logros cinematográficos, entre ellos dos Premios Óscar ", LargeDesc = "Angelina Jolie Voight (Los Ángeles, California; 4 de junio de 1975) es una actriz, cineasta y embajadora de buena voluntad estadounidense. A lo largo de su carrera, Jolie ha recibido varios reconocimientos por sus logros cinematográficos, entre ellos dos Premios Óscar (uno a mejor actriz de reparto y el premio humanitario), tres Globos de Oro y dos Premios del Sindicato de Actores. Desde 2012 es Enviada Especial del Alto Comisionado de las Naciones Unidas para los Refugiados. En 2016 la London School of Economics anunció que Jolie sería profesora de un nuevo tipo de máster sobre «Las mujeres, la paz y la seguridad» con el objetivo de promover la igualdad de género y ayudar a las mujeres afectadas por los conflictos de todo el mundo.  Aunque comenzó actuando en 1982 junto con su padre Jon Voight, se le atribuye como debut oficial su papel en la película Cyborg 2 de 1993. La primera interpretación principal que hizo fue en la película Hackers de 1995. En 1997 actuó en la polémica película George Wallace. Interpretó a un personaje principal en el filme para televisión GIA en 1998. Su reconocimiento mundial comenzó a desarrollarse después de que ganara un premio Óscar como mejor actriz de reparto en 2000 gracias a su trabajo en la película Inocencia interrumpida."},
                new Actriz{ Nombre = "Penélope Cruz", Foto = "actriz5.jpg", Desc = "Penélope Cruz Sánchez, más conocida como Penélope Cruz, es una actriz española. En 2006 fue la primera actriz española candidata a los Premios Óscar y a los Globos de Oro en la categoría de mejor actriz protagonista", LargeDesc = "Penélope Cruz Sánchez (Alcobendas, 28 de abril de 1974), más conocida como Penélope Cruz, es una actriz española. En 2006 fue la primera actriz española candidata a los Premios Óscar y a los Globos de Oro en la categoría de mejor actriz protagonista, por su papel en la película española Volver, dirigida por el cineasta español Pedro Almodóvar; en esa ocasión no obtuvo el Óscar, pero en el año 2009 se convirtió en la primera actriz española en conseguir el Óscar como mejor actriz de reparto gracias a la película Vicky Cristina Barcelona dirigida por Woody Allen. Con esta película ganó además el premio BAFTA, su tercer Goya, y fue nominada a los Globos de Oro y al Premio del Sindicato de Actores. Penélope volvió a ser nominada al Óscar como mejor actriz de reparto de 2010 por su papel en Nine y en 2022 en la categoría de mejor actriz protagonista por su papel en la película de Almodóvar, Madres paralelas. En 2018 recibió Medalla de Oro al Mérito en las Bellas Artes, concedida por el Gobierno de España. En 2019 recibió el Premio Donostia y fue el rostro identificativo del 67 Festival de cine de San Sebastián."},
                new Actriz{ Nombre = "Charlize Theron", Foto = "actriz6.jpg", Desc = "Charlize Theron es una actriz y modelo sudafricana-estadounidense. Alcanzó la fama después de participar en varias producciones cinematográficas en la década de los noventa", LargeDesc = "Charlize Theron (Benoni; 7 de agosto de 1975) es una actriz y modelo sudafricana-estadounidense. Alcanzó la fama después de participar en varias producciones cinematográficas en la década de los noventa, entre las que se destacan The Devil's Advocate (1997), Mighty Joe Young (1998) y The Cider House Rules (1999). En 2003 fue acreedora del Óscar a la mejor actriz por su interpretación de la asesina en serie Aileen Wuornos en la película Monster, lo que la convirtió en la primera africana en recibir el premio en esa categoría. Dos años después recibió por segunda vez una nominación al Óscar por su actuación en North Country.  Desde 2007 Theron es ciudadana estadounidense, aunque aún conserva su ciudadanía sudafricana. Además tiene una participación especial como Clea en la escena postcrédito de Doctor Strange en el Multiverso de la Locura (2022). "},
                new Actriz{ Nombre = "Demi Moore", Foto = "actriz7.jpg", Desc = "Demetria Gene Guynes, conocida profesionalmente como Demi Moore, es una actriz, modelo y productora estadounidense. Después de realizar papeles pequeños en películas y un papel recurrente en la serie de televisión General Hospital, Moore estableció su carrera en la década de 1990.", LargeDesc = "Demetria Gene Guynes (Roswell, Nuevo México, 11 de noviembre de 1962), conocida profesionalmente como Demi Moore, es una actriz, modelo y productora estadounidense. Después de realizar papeles pequeños en películas y un papel recurrente en la serie de televisión General Hospital, Moore estableció su carrera en la década de 1990. Su actuación protagónica en Ghost, la película más taquillera de 1990, le valió una nominación a los Globos de Oro. Acto seguido apareció en películas con buenos resultados en taquilla como A Few Good Men (1992), Indecent Proposal (1993) y Disclosure (1994). En 1996 recibió doce millones y medio de dólares por protagonizar la película Striptease. Para su siguiente película, G.I. Jane (1997), la actriz tuvo que afeitar su cabeza para interpretar a la primera mujer en los comandos SEAL. A partir de entonces su popularidad en Hollywood empezó a decrecer y la actriz empezó a dedicar más tiempo a su familia. Sus créditos en cine a partir de la década del 2000 incluyen producciones como Charlie's Angels: Full Throttle (2003), Bobby (2006), Mr. Brooks (2007) y Margin Call (2011). Moore tomó su nombre profesional de su primer esposo, el músico Freddy Moore. Es madre de tres hijas de su segundo matrimonio con Bruce Willis. Se casó con su tercer esposo, el actor Ashton Kutcher en 2005, y se divorció de él en 2011."},
                new Actriz{ Nombre = "Nicole Kidman", Foto = "actriz8.jpg", Desc = "Nicole Mary Kidman, es una actriz, productora y cantante australiana-estadounidense. Ha recibido numerosos galardones, incluidos un Premio Óscar, un Premio BAFTA, un Premio del Sindicato de Actores de la Pantalla, dos Premios Primetime Emmy y seis Globos de Oro. ", LargeDesc = "Nicole Mary Kidman, AO (Honolulu, Hawái; 20 de junio de 1967), es una actriz, productora y cantante australiana-estadounidense. Ha recibido numerosos galardones, incluidos un Premio Óscar, un Premio BAFTA, un Premio del Sindicato de Actores de la Pantalla, dos Premios Primetime Emmy y seis Globos de Oro. Ha aparecido tres veces en los rankings anuales de las actrices mejor pagadas del mundo y fue nombrada por la revista Time como una de las 100 personas más influyentes del mundo en 2004 y 2018. En 2020, The New York Times la clasificó en quinto lugar en su lista de los mejores actores y actrices del siglo XXI hasta ese momento. Kidman comenzó su carrera como actriz en Australia con las películas de 1983, Bush Christmas y Los Bicivoladores. Su gran avance se produjo en 1989 con la película de suspenso Dead Calm y la miniserie Bangkok Hilton. En 1990, hizo su debut en Hollywood en la película de coches de carrera Days of Thunder, junto a Tom Cruise. Luego logró un mayor reconocimiento con papeles principales en Far and Away (1992), Batman Forever (1995), Todo por un sueño (1995) y Eyes Wide Shut (1999). Kidman ganó el Premio Óscar a la Mejor Actriz por interpretar a la escritora Virginia Woolf en el drama Las horas (2002). Sus otros papeles nominados al Oscar fueron como cortesana en el musical Moulin Rouge! (2001); madres con problemas emocionales en los dramas Rabbit Hole (2010) y Lion (2016); y la actriz Lucille Ball en Being the Ricardos (2021). Otros créditos cinematográficos de Kidman incluyen The Others (2001), Cold Mountain (2003), Dogville (2003), Birth (2004), Australia (2008), The Paperboy (2012), Paddington (2014), The Killing of a Sacred Deer (2017), Destroyer (2018), Aquaman (2018) y Bombshell (2019). Sus películas han recibido elogios por parte de la crítica y en la década de 2000 sería considerada una de las mejores actrices del mundo. En 2003, Kidman consiguió tener su estrella en el Paseo de la Fama de Hollywood en Hollywood, California."},
            };

            lsvGrupo2.ItemsSource = grupo2;

        }
        //CUando se presiona se abre la página Descripcion_Actriz con el item seleccionado
        private async void lsvGrupo2_ItemTapped(object sender, ItemTappedEventArgs e)
        {

            Actriz item = (Actriz)e.Item;
            if (item != null)
            {
                await Navigation.PushAsync(new Descripcion_Actriz(item));
            }

        }
    }
}
